project:
  type: website
  output-dir: _site
  # Exclude advanced posts that require heavy computation
  render:
    - "*.qmd"
    - "!advanced_posts/"

website:
  title: "BendThe-Curve"
  site-url: "https://ram-polisetti.github.io/BendTheCurve/"
  repo-url: "https://github.com/ram-polisetti/BendTheCurve"
  page-navigation: true
  comments: false
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Posts"
        file: posts.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/ram-polisetti/BendTheCurve
      - icon: twitter
        href: https://twitter.com

  sidebar:
    style: docked
    contents:
      - section: "Topics"
        contents:
          - text: "Machine Learning"
            href: posts.qmd#category=machine-learning
          - text: "Deep Learning"
            href: posts.qmd#category=deep-learning
          - text: "Data Science"
            href: posts.qmd#category=data-science
          - text: "Data Visualization"
            href: posts.qmd#category=data-visualization
          - text: "Python"
            href: posts.qmd#category=python
          - text: "Tutorials"
            href: posts.qmd#category=tutorial
      - section: "Advanced Topics"
        contents:
          - text: "Note: Advanced posts with heavy computations are currently under maintenance"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    include-in-header:
      text: |
        <script>
          window.addEventListener('load', function() {
            // Function to handle related posts
            function setupRelatedPosts() {
              const relatedPostsData = document.querySelector('meta[name="related-posts"]')?.content;
              if (relatedPostsData) {
                try {
                  const posts = JSON.parse(relatedPostsData);
                  if (posts && posts.length > 0) {
                    const container = document.createElement('div');
                    container.className = 'related-posts';
                    container.innerHTML = `
                      <h2 class="related-posts-title">Related Posts</h2>
                      <div class="related-posts-grid">
                        ${posts.map(post => `
                          <div class="related-post-card">
                            <a href="${post.path}" class="related-post-link">
                              <h3 class="related-post-title">${post.title}</h3>
                              ${post.description ? `<p class="related-post-description">${post.description}</p>` : ''}
                              <div class="related-post-meta">
                                ${post.categories ? post.categories.map(cat => `
                                  <span class="related-post-category">${cat}</span>
                                `).join('') : ''}
                              </div>
                            </a>
                          </div>
                        `).join('')}
                      </div>
                    `;
                    document.querySelector('main').appendChild(container);
                  }
                } catch (e) {
                  console.error('Error setting up related posts:', e);
                }
              }
            }
            setupRelatedPosts();
          });
        </script>
        <style>
          .related-posts {
            margin-top: 4rem;
            padding: 2rem;
            background: var(--bs-body-bg);
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          .related-posts-title {
            font-size: 1.75rem;
            margin-bottom: 1.5rem;
            color: var(--bs-body-color);
            border-bottom: 2px solid var(--bs-primary);
            padding-bottom: 0.5rem;
          }
          .related-posts-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1.5rem;
          }
          .related-post-card {
            background: var(--bs-body-bg);
            border: 1px solid var(--bs-border-color);
            border-radius: 6px;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
          }
          .related-post-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
          }
          .related-post-link {
            display: block;
            padding: 1.5rem;
            text-decoration: none;
            color: inherit;
          }
          .related-post-title {
            font-size: 1.25rem;
            margin: 0 0 0.75rem 0;
            color: var(--bs-primary);
          }
          .related-post-description {
            font-size: 0.95rem;
            color: var(--bs-body-color);
            margin-bottom: 1rem;
            opacity: 0.9;
          }
          .related-post-meta {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            font-size: 0.85rem;
          }
          .related-post-category {
            background: var(--bs-primary);
            color: white;
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            font-size: 0.8rem;
          }
        </style>

posts/**/index.qmd:
  format:
    html:
      include-in-header:
        text: |
          <meta name="related-posts" content='{{related_posts}}'>

listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true

execute:
  freeze: auto