project:
  type: website

website:
  title: "BendThe-Curve"
  site-url: "https://ram-polisetti.github.io/BendTheCurve/"
  repo-url: "https://github.com/ram-polisetti/BendTheCurve"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
